In [1]:
import sys
# Ensure we aren't accidentally pulling from Roaming
sys.path = [p for p in sys.path if "Roaming" not in p]

try:
    from scipy import sparse
    import sklearn
    print("Success! Scipy Sparse and Sklearn are both loaded.")
except ImportError as e:
    print(f"Still failing: {e}")

Success! Scipy Sparse and Sklearn are both loaded.

In [2]:
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
#from langchain_community.chains import LLMChain
import json
from langchain_community.llms import Ollama
import os
import urllib.request
from pathlib import Path
from dotenv import load_dotenv
from sklearn.model_selection import train_test_split
import pandas as pd
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import OllamaEmbeddings
#from langchain.evaluation import load_evaluator
from datasets import Dataset
from ragas.metrics.collections import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from ragas.llms import LangchainLLMWrapper
from datasets import load_dataset
from langchain_core.prompts import ChatPromptTemplate
from ragas import evaluate
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
from openai import OpenAI
from ragas.llms import llm_factory
from ragas.embeddings import embedding_factory
from ragas.metrics.base import Metric


load_dotenv()

c:\Users\Public\anaconda3\envs\agenticEnv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\4194381195.py:31: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\4194381195.py:31: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\4194381195.py:31: DeprecationWarning: Importing AnswerCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerCorrectness
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\4194381195.py:31: DeprecationWarning: Importing ContextUtilization from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextUtilization
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\4194381195.py:31: DeprecationWarning: Importing ContextPrecision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextPrecision
  from ragas.metrics import Faithfulness, AnswerRelevancy, AnswerCorrectness, ContextUtilization, ContextPrecision

True

In [3]:
openai_api_key = os.getenv("OPENAI_API_KEY")

In [4]:
os.makedirs("../data", exist_ok=True)
urllib.request.urlretrieve("https://arxiv.org/pdf/2502.17429?", "../data/incremental_learning_semantic_seg.pdf")
pdf = Path("../data/incremental_learning_semantic_seg.pdf")
print(pdf.exists(), pdf.stat().st_size)

True 2342202

In [5]:
loader = PyPDFLoader("../data/incremental_learning_semantic_seg.pdf")
documents = loader.load()

splitter = RecursiveCharacterTextSplitter(chunk_size = 700, chunk_overlap = 100)
chunks = splitter.split_documents(documents=documents)
print(f"Total Chunks Created : {len(chunks)}")

Total Chunks Created : 117

In [ ]:
# llm = Ollama(
#     model="qwen2.5",
#     temperature=0.2,
#     top_p=0.9,
#     num_ctx=4096
# )

# Model used to generate the synthetic dataset:
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.1, api_key=openai_api_key)

In [ ]:
# Prompt to generate synthetic dataset:
rag_prompt = PromptTemplate(
    input_variables=["context"],
    template="""
You are a teacher/professor.

Given the context below:
- Generate ONE high-quality, non-trivial question
- The question MUST be answerable ONLY from the context
- Provide a concise, factual answer
- Do NOT use external knowledge

Context:
{context}

Return JSON:
{{
  "question": "...",
  "answer": "...",
  "context": "..."
}}
"""
)

rag_chain = rag_prompt | llm

In [8]:
dataset = []

def create_dataset(chunks, rag_chain):
    dataset = []
    
    for chunk in chunks:
        
        response = rag_chain.invoke(input={
            'context' : chunk.page_content
        })

        try:
            res_text = json.loads(response.content)
            dataset.append(res_text)
            
        except Exception as e:
            print(f"Error : {str(e)}")

    return dataset

In [9]:
qa_dataset = create_dataset(chunks, rag_chain=rag_chain)

Error : Invalid control character at: line 4 column 142 (char 291)

In [10]:
qa_dataset

[{'question': 'What is the main focus of the research presented in the paper by Thengane et al.?',
  'answer': 'The main focus of the research is on Class-Incremental Imbalanced 3D Instance Segmentation (CLIMB-3D).',
  'context': 'arXiv:2502.17429v3  [cs.CV]  21 Nov 2025 THENGANE ET AL.: CLIMB-3D1 CLIMB-3D: Class-Incremental Imbalanced 3D Instance Segmentation Vishal Thengane1 v.thengane@surrey.ac.uk Jean Lahoud2 jean.lahoud@mbzuai.ac.ae Hisham Cholakkal2 hisham.cholakkal@mbzuai.ac.ae Rao Muhammad Anwer2 rao.anwer@mbzuai.ac.ae Lu Yin1 l.yin@surrey.ac.uk Xiatian Zhu1 xiatian.zhu@surrey.ac.uk Salman Khan2, 3 salman.khan@mbzuai.ac.ae 1 University of Surrey, Guildford, UK 2 Mohamed bin Zayed University of Artificial Intelligence, Abu Dhabi, UAE 3 Australian National University, Canberra, Australia Abstract While 3D instance segmentation (3DIS) has advanced significantly, most existing'},
 {'question': 'What is the main limitation of existing methods in 3D instance segmentation according to the context?',
  'answer': 'Existing methods assume that all object classes are known in advance and uniformly distributed, which is unrealistic in dynamic, real-world environments.',
  'context': 'While 3D instance segmentation (3DIS) has advanced significantly, most existing methods assume that all object classes are known in advance and uniformly distributed. However, this assumption is unrealistic in dynamic, real-world environments where new classes emerge gradually and exhibit natural imbalance.'},
 {'question': 'What is the purpose of the class-balanced re-weighting (CBR) scheme introduced in the context?',
  'answer': 'The CBR scheme estimates object frequencies from pseudo-labels and dynamically adjusts training bias to mitigate the bias towards frequent classes in the pseudo-label generator (PLG).',
  'context': 'ing upon established exemplar replay (ER) strategies, we show that ER alone is insuf- ficient to achieve robust performance under memory constraints. To mitigate this, we introduce a novel pseudo-label generator (PLG) that extends supervision to previously learned categories by leveraging predictions from a frozen model trained on prior tasks. Despite its promise, PLG tends to be biased towards frequent classes. Therefore, we propose a class-balanced re-weighting (CBR) scheme that estimates object frequencies from pseudo-labels and dynamically adjusts training bias, without requiring access to past data. We design and evaluate three incremental scenarios for 3DIS on the challeng-'},
 {'question': 'What dataset is used to evaluate the method for semantic segmentation?',
  'answer': 'ScanNetV2',
  'context': 'past data. We design and evaluate three incremental scenarios for 3DIS on the challenging ScanNet200 dataset and additionally validate our method for semantic segmentation on ScanNetV2. Our approach achieves state-of-the-art results, surpassing prior work by up to 16.76% mAP for instance segmentation and approximately 30% mIoU for semantic segmentation, demonstrating strong generalisation across both frequent and rare classes. Code is available at:https://github.com/vgthengane/CLIMB3D. © 2025. The copyright of this document resides with its authors. It may be distributed unchanged freely in print or electronic forms.'},
 {'question': 'What new object categories are introduced in Task 2 of the CI-3DIS setting?',
  'answer': 'Pillow, Coffee Table, and Sofa Chair.',
  'context': '2THENGANE ET AL.: CLIMB-3D 1 Introduction Table Chair Couch Pillow Coffee Table Sofa Chair Recycling BinCabinet Unknown Task-1 Task-2 Task-3 Figure 1:Overview of the CI-3DIS setting.New object categories are introduced incre- mentally with each task. After every phase, the model must recognise both newly added and previously learned classes. For instance, in Task 2, categories such as Pillow, Coffee Table, and Sofa Chair are introduced, while the model is expected to retain recognition of earlier classes like Table, Chair, and Couch.'},
 {'question': 'What is the primary motivation for the need for Class-Incremental Learning (CIL) in 3D instance segmentation?',
  'answer': 'The primary motivation for the need for Class-Incremental Learning (CIL) in 3D instance segmentation is that traditional methods assume all classes are available and balanced during training, which does not hold in real-world environments where new object classes emerge over time and exhibit natural imbalance.',
  'context': '3D instance segmentation (3DIS) is a fundamental task in computer vision that involves identifying precise object boundaries and class labels in 3D space, with broad applications in graphics, robotics, and augmented reality [4, 39]. Traditional 3DIS methods, including top-down [28, 70, 78], bottom-up [26, 73], and transformer-based approaches [59], perform well under the assumption that all classes are available and balanced during training. However, this assumption does not hold in real-world environments, where new object classes emerge over time and exhibit natural imbalance. This gap motivates the need for Class-Incremental Learning (CIL) [17, 54], which sup-'},
 {'question': 'What does CLIMB-3D aim to address in the context of Class-Incremental Learning?',
  'answer': 'CLIMB-3D aims to address the limitations of existing methods in class-incremental learning for 3D point clouds, particularly the dependence on large exemplars and the issue of class imbalance.',
  'context': 'This gap motivates the need for Class-Incremental Learning (CIL) [17, 54], which supports learning new categories while retaining knowledge of previous ones [51]. While CIL has seen success in 2D image tasks [1, 43, 54, 60], extensions to 3D point clouds remain limited, often focusing on object-level classification [13, 18, 48]. Recent works on scene-level class-incremental 3DIS (CI-3DIS) [4] and class-incremental semantic segmentation (CI-3DSS) [74] show promise, but depend heavily on large exemplar [56] and overlook class imbalance, limiting their practicality. To address this, we propose CLIMB-3D, a unified framework for CLass-incremental.'},
 {'question': 'What is the purpose of the Pseudo-Label Generator (PLG) in the CLIMB-3D framework?',
  'answer': 'The Pseudo-Label Generator (PLG) uses a frozen model from previous tasks to generate supervision for earlier classes.',
  'context': 'To address this, we propose CLIMB-3D, a unified framework for CLass-incremental IMBalance-aware 3DIS that jointly tackles catastrophic forgetting and class imbalance. The framework begins with Exemplar Replay (ER), storing a small number of samples from past classes for later replay. However, this alone does not yield promising results under the strict memory constraints required in CI-3DIS. To address this, we introduce a Pseudo-Label Generator (PLG), which uses a frozen model from previous task to generate supervision for earlier classes. However, we observed that PLG tends to favour frequent classes while ig-'},
 {'question': 'What is the purpose of Class-Balanced Re-weighting (CBR) in the context of CLIMB-3D?',
  'answer': 'The purpose of Class-Balanced Re-weighting (CBR) is to enhance the learning of rare classes by estimating class frequencies from the pseudo-labels, without accessing past data.',
  'context': 'earlier classes. However, we observed that PLG tends to favour frequent classes while ignoring under-represented ones. To mitigate this, we propose a Class-Balanced Re-weighting (CBR), which estimates class frequencies from the pseudo-labels to enhance the learning of rare classes without accessing past data. Together, these components form a practical and effective solution for real-world 3DIS.'},
 {'question': 'What dataset is used for evaluating the approach on CI-3DSS?',
  'answer': 'ScanNetV2 dataset',
  'context': 'ural class imbalance, where new classes emerge based on (A) object frequency, (B) semantic similarity, or (C) random grouping. Additionally, for comparison with existing methods, we evaluate our approach on CI-3DSS using the ScanNetV2 dataset [16]. Experimental re- sults show that our method significantly reduces forgetting and improves performance across both frequent and rare categories, outperforming previous methods in both settings. Fig. 1 illustrates the CI-3DIS setup.'},
 {'question': 'What is one of the main contributions of Thengane et al. in their work on imbalanced class-incremental 3D instance segmentation?',
  'answer': 'A novel problem setting of imbalanced class-incremental 3DIS with an effective method to balance learning and mitigate forgetting.',
  'context': 'THENGANE ET AL.: CLIMB-3D3 In summary, our contributions are: (i) a novel problem setting of imbalanced class-incremental 3DIS with an effective method to balance learning and mitigate forgetting; (ii) three benchmarks modelling continual object emergence with natural imbalance; and (iii) strong experimental results, achieving up to 16.76% mAP improvement over baselines.'},
 {'question': 'What is a limitation of transformer-based models applied to 3DIS and 3DSS?',
  'answer': 'They require full annotations for all classes and are not designed for progressive learning.',
  'context': 'ing [9, 21, 22, 29, 37, 44, 70, 78]. In contrast, proposal-based methods follow a top-down strategy by detecting 3D boxes and segmenting objects within them [19, 26, 46, 73, 76]. Recently, transformer-based models [68] have also been applied to 3DIS and 3DSS [59, 64], inspired by advances in 2D vision [10, 11]. However, these approaches require full annotations for all classes and are not designed for progressive learning, where only new class annotations are available and previous data is inaccessible. Another line of work aims to re-duce annotation costs by proposing weakly supervised 3DIS methods based on sparse cues.'},
 {'question': 'What is one common strategy used in incremental learning to mitigate catastrophic forgetting?',
  'answer': 'Model regularisation, which constrains parameter updates using techniques such as elastic weight consolidation or knowledge distillation.',
  'context': 'duce annotation costs by proposing weakly supervised 3DIS methods based on sparse cues [12, 27, 72]. While effective with limited annotations, these methods assume a fixed set of classes and are susceptible to catastrophic forgetting in incremental settings. Incremental Learning.Continual learning involves training models sequentially to mitigate catastrophic forgetting. One common strategy is model regularisation, which constrains parameter updates using techniques such as elastic weight consolidation or knowledge distillation [1, 24, 35, 43, 60]. Another approach is exemplar replay, where past data is stored.'},
 {'question': 'What is one method mentioned for rehearsing older tasks while learning new ones?',
  'answer': 'Exemplar replay, where past data is stored or generated.',
  'context': 'tillation [1, 24, 35, 43, 60]. Another approach is exemplar replay, where past data is stored or generated to rehearse older tasks while learning new ones [5, 7, 30, 54]. A third direc- tion involves dynamically expanding the model architecture or using modular sub-networks to accommodate new tasks without interfering with old ones [31, 42, 53, 58, 71, 79]. Re- cent efforts in class-incremental 3D segmentation [63, 74] have shown early promise but often rely on basic architectures and focus primarily on semantic segmentation. Other works [4, 36] explore continual learning in 3D settings, though they often depend on large memory.'},
 {'question': 'What problem does the tailored framework for 3D instance segmentation aim to address?',
  'answer': 'The tailored framework aims to effectively transfer knowledge across tasks, even under class imbalance.',
  'context': '[4, 36] explore continual learning in 3D settings, though they often depend on large memory buffers. In contrast, our work introduces a tailored framework for 3D instance segmentation that effectively transfers knowledge across tasks, even under class imbalance.'},
 {'question': 'What dataset is mentioned in the context that enables efforts similar to long-tailed recognition in 3D?',
  'answer': 'ScanNet200',
  'context': 'offers another direction, using class-based [6, 15, 23, 32, 33, 69] or per-example [45, 55, 62] adjustments to ensure fair contribution. Parameter regularisation improves generalisation through weight constraints [2], albeit requiring careful tuning. Other approaches leverage transfer learning [77, 81], self-supervision [41, 75], or contrastive learning [34, 41, 82] to improve rare-class representations. Long-tailed recognition is well-studied in 2D with large-scale datasets [15, 49, 67]; in 3D, ScanNet200 [16, 57] enables similar efforts. Prior 3D work focused on re-weighting, re-sampling, and transfer learning [57], while regularisation.'},
 {'question': 'What aspect of 3D semantic segmentation is jointly addressed in the discussed work?',
  'answer': 'Long-tail and continual 3D semantic segmentation.',
  'context': 'work focused on re-weighting, re-sampling, and transfer learning [57], while regularisation remains underexplored. CeCo [80] balances class centres via auxiliary loss but overlooks sampling and augmentation. Lahoud et al. [38] propose adaptive classifier regularisation for 3D segmentation, outperforming prior approaches without threshold tuning. However, neither method considers incremental learning. In contrast, we jointly address long-tail and continual 3D semantic segmentation.'},
 {'question': 'What method does CLIMB-3D use to maintain a small memory of past examples during incremental learning?',
  'answer': 'Exemplar Replay (ER)',
  'context': '4THENGANE ET AL.: CLIMB-3D Feature Backbone Transformer Decoder Feature Backbone Transformer Decoder (𝑷,𝒀𝑡) Current model (𝛷 𝑡) Pseudo Label Generator (PLG) Selection ෨𝑌𝐾 𝑡 ℒCI−3DIS ෨𝑌𝐾 𝑡,𝑤 ത𝑌𝐾 𝑡 \u0de0𝑌𝑡 (𝐷𝑡) Current Dataset Exemplar Replay (ER) + ~ Class-Balanced Re-weighting (CBR) 1 𝑓(𝑐) Figure 2: Overview ofCLIMB-3Dfor CI-3DIS. The model incrementally learns new classes across sequential phases. During taskt, point cloudsPand their corresponding labelsY t are sampled from a combination of the current training datasetD t and Exemplar Replay (ER), which maintains a small memory of past examples. These are then passed to the current.'},
 {'question': 'What is the purpose of the Class-Balanced Re-weighting (CBR) in the pseudo-label generation process?',
  'answer': 'The purpose of Class-Balanced Re-weighting (CBR) is to weight the pseudo-labels based on class frequency f(c) to ensure a balanced pseudo-label set.',
  'context': 'which maintains a small memory of past examples. These are then passed to the current modelΦ t to produce predicted labelsY t . The Pseudo-Label Generator (PLG) selects the top-K predictions from the previous modelΦ t−1 . These pseudo-labels are then weighted based on class frequencyf(c) using Class-Balanced Re-weighting (CBR), and the top-K re-weighted labels are selected to form the balanced pseudo-label set ¯Yt . This pseudo-label set is then concatenated with the ground-truth labels to form a final augmented supervision set Yt for taskt, which is used to optimise the modelΦ t using Eq. (3).'},
 {'question': 'What does the binary mask mi,j indicate in the context of the training dataset?',
  'answer': 'The binary mask mi,j indicates which points belong to the j-th instance within the point cloud.',
  'context': '3 Methodology 3.1 Problem Formulation 3DIS.The objective of this task is to detect and segment each object instance within a point cloud. Formally, the training dataset is denoted as D={(P i,Yi)}N i=1, where N is the number of training samples. Each input P i ∈R M×6 is a coloured point cloud consisting of M points, where each point is represented by its 3D coordinates and RGB values. The corresponding annotation Y i ={(m i,j ,ci,j )}Ji j=1 contains J i object instances, where mi,j ∈ {0,1}M is a binary mask indicating which points belong to the j-th instance, and ci,j ∈ C={1,...,C} is the semantic class label of that instance. Given P i, the model Φ predicts instance-level outputs ˆYi ={(ˆmi,j ,ˆci,j )}.'},
 {'question': 'What does the variable λ represent in the objective function L3DIS?',
  'answer': 'The variable λ controls the trade-off between the average classification loss L cls and the average mask loss L mask in the objective function.',
  'context': 'ˆYi ={(ˆmi,j ,ˆci,j )} ˆJi j=1, where ˆmi,j and ˆci,j denote the predicted mask and category label for the j-th instance, respectively. The number of predicted instances ˆJi varies depending on the model’s inference. The model is optimised using the following objective: L3DIS(D;Φ) = 1 |D| ∑ (P,Y)∈D 1 |Y| ∑ (mj,cj)∈Y (Lmask(mj,ˆmj)+λ·L cls(cj,ˆcj)),(1) where L cls and L mask are the average classification and mask losses over all instances, and λ controls their trade-off. CI-3DIS. Unlike conventional 3DIS, CI-3DIS involves sequential learning, where object categories are introduced incrementally over T training tasks. Each task t introduces a disjoint set of classes C t, with C= ST.'},
 {'question': "What is the relationship between the classes Ct and Ct' when t is not equal to t'?",
  'answer': 'C t ∩ C t′ ≠ 0 for t ≠ t′.',
  'context': 'joint set of classesC t , withC= ST t=1 Ct andC t ∩C t′ ≠ 0 fort̸=t ′. During each taskt, the'},
 {'question': 'What is the primary challenge faced by the model Φ t when learning new classes?',
  'answer': 'The primary challenge is to learn new classes without forgetting those encountered in previous tasks, despite limited supervision and the absence of past labels.',
  'context': 'THENGANE ET AL.: CLIMB-3D5 model receives a dataset D t ={(P i,Yt i)}N i=1, where each coloured point cloud P i ∈R M×6 contains M points, and the corresponding annotation Y t i ={(m t i,j ,ct i,j )}Jt i j=1 includes instance masks m t i,j ∈ {0,1}M and semantic class labels c t i,j ∈ Ct . The model Φ t , initialized from Φt−1 , is trained on D t to predict instance-level outputs ˆYt i ={(ˆmt i,j ,ˆct i,j )}ˆJt i j=1, where each predicted semantic label ˆct i,j belongs to the cumulative set of all classes observed so far: St k=1 Ck. The key challenge in this setup is to learn new classes without forgetting those encountered in previous tasks, despite limited supervision and the absence of past labels.'},
 {'question': 'What strategy is incorporated to address catastrophic forgetting in the CI-3DIS framework?',
  'answer': 'Exemplar Replay (ER)',
  'context': 'encountered in previous tasks, despite limited supervision and the absence of past labels. 3.2 Method: CLIMB-3D Overview.As shown in Fig. 2 and formulated in Sec. 3.1, the proposed framework for CI-3DIS follows a phase-wise training strategy. In each phase, the model is exposed to a carefully curated subset of the dataset, simulating real-world scenarios discussed in Sec. 3.3. Training naïvely on such phased data leads to catastrophic forgetting, where the model forgets prior knowledge when learning new tasks. To address this, we first incorporate Exemplar Replay (ER), a strategy inspired by 2D incremental methods.'},
 {'question': 'What are the two additional components introduced alongside Emplar Replay to improve performance?',
  'answer': 'The two additional components are the Pseudo-Label Generator (PLG) and the Class-Balanced Re-weighting (CBR) module.',

In [11]:
len(qa_dataset[:10])

10

In [12]:
train_examples, test_examples = train_test_split(
    qa_dataset,
    test_size=0.2,          # 20% held out
    random_state=42,        # for reproducibility
    shuffle=True
)

print(f"Training on {len(train_examples)} examples, testing on {len(test_examples)} examples")

Training on 92 examples, testing on 24 examples

In [13]:
test_dataset = pd.DataFrame.from_records(data=test_examples)
test_dataset.head()

,question,answer,context
0,What is the main focus of the paper by Saining...,The main focus of the paper by Saining Xie et ...,"16THENGANE ET AL.: CLIMB-3D [71] Zifeng Wang, ..."
1,What new object categories are introduced in T...,"Pillow, Coffee Table, and Sofa Chair.",2THENGANE ET AL.: CLIMB-3D 1 Introduction Tabl...
2,What metric is used to assess the model's abil...,Forgetting Percentage Points (FPP),we report the mean Intersection over Union (mI...
3,What dataset is used to evaluate CLIMB-3D in t...,ScanNet200,These incremental scenarios are designed to pr...
4,What is one of the main contributions of Theng...,A novel problem setting of imbalanced class-in...,"THENGANE ET AL.: CLIMB-3D3 In summary, our con..."

In [17]:
test_dataset.to_csv("../data/test_dataset.csv", index=False)

In [14]:
train_examples[0]

{'question': 'What dataset is mentioned in the context that enables efforts similar to long-tailed recognition in 3D?',
 'answer': 'ScanNet200',
 'context': 'offers another direction, using class-based [6, 15, 23, 32, 33, 69] or per-example [45, 55, 62] adjustments to ensure fair contribution. Parameter regularisation improves generalisation through weight constraints [2], albeit requiring careful tuning. Other approaches leverage transfer learning [77, 81], self-supervision [41, 75], or contrastive learning [34, 41, 82] to improve rare-class representations. Long-tailed recognition is well-studied in 2D with large-scale datasets [15, 49, 67]; in 3D, ScanNet200 [16, 57] enables similar efforts. Prior 3D work focused on re-weighting, re-sampling, and transfer learning [57], while regularisation.'}

In [33]:
def create_train_dataset(train_examples, out_path):
    
    with open(out_path, "w+", encoding="utf8") as f:
        for example in train_examples:
            content = {
                "messages" : [
                    {"role":"user", "content": example['question']},
                    {"role":"assistant", "content":example['answer']}
                ]
            }
            f.write(json.dumps(content, ensure_ascii=False) +"\n")
    return "Train Dataset Created"

In [35]:
create_train_dataset(train_examples, "../data/train_dataset.jsonl")

'Train Dataset Created'

In [42]:
train_dataset = load_dataset("json", data_files="../data/train_dataset.jsonl")
print(train_dataset)
print(train_dataset['train'][:5])

DatasetDict({
    train: Dataset({
        features: ['messages'],
        num_rows: 92
    })
})
{'messages': [[{'role': 'user', 'content': 'What dataset is mentioned in the context that enables efforts similar to long-tailed recognition in 3D?'}, {'role': 'assistant', 'content': 'ScanNet200'}], [{'role': 'user', 'content': 'What is the title of the work by Li Jiang et al. presented at CVPR in 2020?'}, {'role': 'assistant', 'content': 'Pointgroup: Dual-set point grouping for 3d instance segmentation.'}], [{'role': 'user', 'content': 'What is the purpose of using the pseudo-label predictions of the frozen model Φ t−1 in the context of class imbalance?'}, {'role': 'assistant', 'content': 'The purpose is to leverage the pseudo-label predictions as a proxy for the class distribution across previously learned categories, allowing for the accumulation of class-wise frequency statistics for those classes.'}], [{'role': 'user', 'content': 'What are the two additional components introduced to enhance the performance of Emplar Replay (ER)?'}, {'role': 'assistant', 'content': 'A Pseudo-Label Generator (PLG) and a Class-Balanced Re-weighting (CBR) module.'}], [{'role': 'user', 'content': 'What challenge does the work address in class-incremental 3D instance segmentation?'}, {'role': 'assistant', 'content': 'The work addresses the challenge of catastrophic forgetting.'}]]}

RAG Evaluation

In [15]:
embeddings = OllamaEmbeddings(model="nomic-embed-text")

C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_10772\2083950908.py:1: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the `langchain-ollama package and should be used instead. To use it run `pip install -U `langchain-ollama` and import as `from `langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model="nomic-embed-text")

In [17]:
test_examples[0]

{'question': 'What is the main focus of the paper by Saining Xie et al. presented at ECCV?',
 'answer': 'The main focus of the paper by Saining Xie et al. is on unsupervised pre-training for 3D point cloud understanding.',
 'context': '16THENGANE ET AL.: CLIMB-3D [71] Zifeng Wang, Tong Jian, Kaushik Chowdhury, Yanzhi Wang, Jennifer Dy, and Stratis Ioannidis. Learn-prune-share for lifelong learning. In2020 IEEE International Conference on Data Mining (ICDM), pages 641–650. IEEE, 2020. [72] Saining Xie, Jiatao Gu, Demi Guo, Charles R Qi, Leonidas Guibas, and Or Litany. Pointcontrast: Unsupervised pre-training for 3d point cloud understanding. InECCV, pages 574–591. Springer, 2020. [73] Bo Yang, Jianan Wang, Ronald Clark, Qingyong Hu, Sen Wang, Andrew Markham, and Niki Trigoni. Learning object bounding boxes for 3d instance segmentation on point clouds.NeurIPS, 32, 2019.'}

In [21]:
# Model we are aiming to fine-tune:
from langchain_community.chat_models import ChatOllama
ft_model = ChatOllama(
    model="llama3.2:1b",
    temperature=0.0
)

In [ ]:
# Prompt used to get answers on the model that we are aiming to fine-tune:
ft_prompt = ChatPromptTemplate.from_template(
    template="""
You are answering a question using retrieved context from a document.

Instructions:
- Use ONLY the information in the context.
- You MAY paraphrase, summarize, and combine information.
- If the context provides partial information, answer as fully as possible.
- Do NOT introduce facts not supported by the context.
- Only say "I don't know" if the context gives no useful information at all.

Context:
{context}

Question:
{question}
"""
)

ft_chain = ft_prompt | ft_model

In [44]:
def generate_answers(dataset, chain):
    test_df = []
    for example in dataset:
        res = chain.invoke(input={
            'question': example['question'],
            'context': example['context']
        })
        response = res.content
        obj = {
            'question' : example['question'],
            'contexts' : example['context'],
            'ground_truth' : example['answer'],
            'base_model_answer' : response
        }
        test_df.append(obj)

    test_generated_dataset = pd.DataFrame.from_records(data=test_df)
    return test_generated_dataset

In [45]:
test_generated_dataset = generate_answers(test_examples, ft_chain)
test_generated_dataset.head()

,question,contexts,ground_truth,base_model_answer
0,What is the main focus of the paper by Saining...,"16THENGANE ET AL.: CLIMB-3D [71] Zifeng Wang, ...",The main focus of the paper by Saining Xie et ...,"The main focus of the paper ""Pointcontrast: Un..."
1,What new object categories are introduced in T...,2THENGANE ET AL.: CLIMB-3D 1 Introduction Tabl...,"Pillow, Coffee Table, and Sofa Chair.",I don't know.
2,What metric is used to assess the model's abil...,we report the mean Intersection over Union (mI...,Forgetting Percentage Points (FPP),To answer this question based on the provided ...
3,What dataset is used to evaluate CLIMB-3D in t...,These incremental scenarios are designed to pr...,ScanNet200,The dataset used to evaluate CLIMB-3D in the e...
4,What is one of the main contributions of Theng...,"THENGANE ET AL.: CLIMB-3D3 In summary, our con...",A novel problem setting of imbalanced class-in...,One of the main contributions of Thengane et a...

In [52]:
test_generated_dataset.rename(columns={'base_model_answer':'answer'},inplace=True)

In [54]:
test_generated_dataset.to_csv("../data/testEvalData_baseModel.csv", index=False)

In [3]:
test_generated_dataset = pd.read_csv("../data/testEvalData_baseModel.csv")

In [ ]:
def get_rag_evaluation(embed_name, dataset, model_name):
    
    
    ragas_data = []
    for _, row in dataset.iterrows():
        
        obj ={
            'question' : row['question'],
            'contexts' : [row['contexts']],
            'ground_truth' : row['ground_truth'],
            'answer' : row['answer']
            
        }
        ragas_data.append(obj)
    
    data = Dataset.from_list(ragas_data)

    # 1. Setup an OpenAI-compatible client for Ollama
    # Ollama provides an OpenAI-compatible endpoint at /v1 --> If any other model to be used here:
    client = OpenAI()

    # 2. Use the llm_factory instead of LangchainLLMWrapper
    # Use provider="openai" to use the compatible client
    #LLM given here is the judge. So, use the same LLM that is used to generate this synthetic data
    evaluator_llm = llm_factory(model_name, client=client)

    #Throwing some errors so switched to LangchainEmbeddingsWrapper:
    # evaluator_embeddings = embedding_factory("openai", model=embed_name, client=client)

    lc_embeddings = OllamaEmbeddings(
    model=embed_name  # e.g. "nomic-embed-text"
    )
    ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)
    
    #Defining the metrics
    m1 = Faithfulness(llm=evaluator_llm)
    m2 = AnswerRelevancy(llm=evaluator_llm, embeddings=ragas_embeddings)
    m3 = AnswerCorrectness(llm=evaluator_llm, embeddings=ragas_embeddings)
    m4 = ContextPrecision(llm=evaluator_llm)

    metric_list = [m1, m2, m3, m4]
    
    results = evaluate(dataset=data,
                       metrics=metric_list,
                       embeddings=ragas_embeddings,
                        )
    eval_df = results.to_pandas()
    return eval_df

In [11]:
eval_df = get_rag_evaluation(embed_name="nomic-embed-text", dataset=test_generated_dataset, 
                             model_name="gpt-4o-mini") #Using the same model that we used earlier to generate the synthetic data
eval_df.head()

C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\1015740776.py:25: DeprecationWarning: Importing embedding_factory from ragas.embeddings is deprecated. Import directly from ragas.embeddings.base or use modern providers: from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  evaluator_embeddings = embedding_factory("openai", model=embed_name, client=client)
C:\Users\Namrata Thakur\AppData\Local\Temp\ipykernel_3428\1015740776.py:30: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(lc_embeddings)
Evaluating:   0%|          | 0/96 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   1%|          | 1/96 [03:19<5:15:41, 199.39s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  14%|█▎        | 13/96 [05:42<30:46, 22.24s/it]  LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  27%|██▋       | 26/96 [08:09<18:24, 15.78s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  41%|████      | 39/96 [10:39<13:06, 13.80s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  54%|█████▍    | 52/96 [13:29<09:55, 13.53s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  67%|██████▋   | 64/96 [15:46<06:50, 12.82s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  80%|████████  | 77/96 [18:00<03:46, 11.93s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating: 100%|██████████| 96/96 [18:39<00:00, 11.66s/it]

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,answer_correctness,context_precision
0,What is the main focus of the paper by Saining...,"[16THENGANE ET AL.: CLIMB-3D [71] Zifeng Wang,...","The main focus of the paper ""Pointcontrast: Un...",The main focus of the paper by Saining Xie et ...,0.666667,0.000000,0.838266,1.0
1,What new object categories are introduced in T...,[2THENGANE ET AL.: CLIMB-3D 1 Introduction Tab...,I don't know.,"Pillow, Coffee Table, and Sofa Chair.",0.000000,0.000000,0.147293,1.0
2,What metric is used to assess the model's abil...,[we report the mean Intersection over Union (m...,To answer this question based on the provided ...,Forgetting Percentage Points (FPP),1.000000,0.697478,0.959224,1.0
3,What dataset is used to evaluate CLIMB-3D in t...,[These incremental scenarios are designed to p...,The dataset used to evaluate CLIMB-3D in the e...,ScanNet200,1.000000,0.866720,0.947993,1.0
4,What is one of the main contributions of Theng...,"[THENGANE ET AL.: CLIMB-3D3 In summary, our co...",One of the main contributions of Thengane et a...,A novel problem setting of imbalanced class-in...,1.000000,0.806459,0.830514,1.0

In [18]:
mean_faithfulness_score = eval_df['faithfulness'].mean()
mean_answer_relevancy_score = eval_df['answer_relevancy'].mean()
mean_answer_correctness_score = eval_df['answer_correctness'].mean()
print(mean_faithfulness_score, mean_answer_relevancy_score, mean_answer_correctness_score)

0.6577380952380952 0.6159300899170209 0.6665186637507786

In [14]:
eval_df.to_csv('../data/baseModel_evaluationScores.csv', index=False)